### ISSUE TITLE
oneplus3 OSS camera hal not working!

### ISSUE THREAD

**Issue by moetayuko** [OnePlusOSS/android_hardware_qcom_camera#1]
Missing vendor changes in .cpp source
@leonfish77101

**Comment by leonfish77101** [comment]
You mean the camera is not working? Please give me more details about this

**Comment by moetayuko** [comment]
You guys only privided vendor changes of headers in https://github.com/OnePlusOSS/android_hardware_qcom_camera/commit/643f8c033cde65dcf19704e67b0cea7ba9089ac8, but those extra functions aren't implemented.
It has no relation to SELinux because camera works with prebuilt camera hal from official release

More detailed, with OSS hal, camera can be opened only once after booting.

**Comment by leonfish77101** [comment]
Camera hal is built from OSS, not pre-built from official release. Can you provide a log about this issue? I think the build process should break if these functions you mentioned are not implement.

BTW, it should be better if you can tell me a line number in 643f8c0.

**Comment by moetayuko** [comment]
I guess it's this one https://github.com/OnePlusOSS/android_hardware_qcom_camera/commit/643f8c033cde65dcf19704e67b0cea7ba9089ac8#diff-03bd04c8408ed45298147f5ac0c239b0R877
Because logcat shows it can't detect camera status.
I'm sorry that I can't provide logcat at this time cause I deleted it

IDK if this matters: https://github.com/OnePlusOSS/android_hardware_qcom_camera/commit/643f8c033cde65dcf19704e67b0cea7ba9089ac8#diff-03bd04c8408ed45298147f5ac0c239b0R798
the two new func have no implementation in hal source, are they completly implemented in proprietary blobs?

**Comment by leonfish77101** [comment]
Interesting... We deleted all codes that invoke have_camera_opened, except a declare. So I don't think this function can cause that issue.
In fact, all functions you mentioned were removed by us from HAL, include implementation and invoktation.  
I want to clarify one information with you: the camera can be opened just once without any code modification? If that, can you tell me the build steps you executed?

**Comment by moetayuko** [comment]
> I want to clarify one information with you: the camera can be opened just once without any code modification?

Yes.
Steps:
https://github.com/dianlujitao/android_device_oneplus_oneplus3/commit/55fcc58fa8711ba15bdd4b88151c99399dd48719
https://github.com/dianlujitao/android_device_oneplus_oneplus3/commit/78a61524ce81f4e8baf1dcd1f21651cea7747b51
Any missing flags?

**Comment by leonfish77101** [comment]
Please download all codes from OnePlusOSS, otherwise I don't know what happens
repo init -u git://github.com/OnePlusOSS/android.git -b oneplus3/6.0.1
repo sync

**Comment by parasaviator** [comment]
please update the kernel sources along with camera blob... you guys havent updated in past 3 OTA 
we have the best devs complaining...update it before they leave this device like they abandoned op2

**Comment by ghost** [comment]
Is there a possibility that you could help out to obtain camera-quality equal to stock OOS on custom-roms? Thanks.
