### ISSUE TITLE
camera api2 / HAL3 is broken (flash issue, no touch to focus)

### ISSUE THREAD

**Issue by RohanAJoshi** [OnePlusOSS/android_hardware_qcom_camera#3]
issue using any 3rd party  api2 app like google camera, snap camera with api2, open camera with api2..
when in dark area, where flash used for focus, then app just focus, cant take picture, camera shutter button disabled.
this also worsening aosp / cm roms experience. ( check this for details : https://jira.cyanogenmod.org/browse/CYAN-7972).
.
This is stock OxygenOS issue, I did not find any proper way to contact developers, so reporting here.
please fix this.
or if I am reporting in wrong section, please guide me to proper way then I will close this issue.

**Comment by leonfish77101** [comment]
Our camera team will check this issue ASAP.

**Comment by RohanAJoshi** [comment]
Thank you so much. :)

**Comment by RohanAJoshi** [comment]
Please, if get any news or information about this, please comment here. 
Thanks.

**Comment by RohanAJoshi** [comment]
In Community build 3.5.2 this issue is fixed. 
Thanks you so much devs. 
I really appreciate this. 
Closing ths.
